#!/usr/bin/env sh

cp spot-download.service /etc/systemd/system/ &&
	systemctl enable spot-download.service

{
	cat /etc/sudoers | grep -v '^arta'
	echo 'arta ALL= NOPASSWD: /usr/bin/systemctl start spot-download.service, /usr/bin/systemctl stop spot-download.service, /usr/bin/systemctl enable spot-download.service, /usr/bin/systemctl restart spot-download.service, /usr/bin/docker load -i spot-download.tar'
} >/etc/sudoers
